baseURL = 'https://skusunoki.github.io/Kampong-Abapagar/'
languageCode = 'en-us'
title = 'Kampong-Abapagar Modern ABAP'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
